# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58d629f47a8a2c823caaf796645dfea1cd8232ab08b9621ba2cece2db573a860007b0ab96f879cff113ef62db777759daba0fb53d9e7a00e8d0874cd10919df1

test:
  secret_key_base: f527b6f3ff420698edb1f5a7bbeb096b79b02972092d0619b4c48624132e3110202bebf0e83aa388f9de0698c0c0f079012466c9ba7b7b81bbe15e3904dbbf8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
